version: 2
updates:
- package-ecosystem: pip
  directory: /ci/scripts
  schedule:
    interval: weekly
    day: "monday"
    time: "09:00"
    timezone: "Europe/Berlin"
- package-ecosystem: gomod
  directory: /src/pcap
  schedule:
    interval: weekly
    day: "monday"
    time: "09:00"
    timezone: "Europe/Berlin"
