version: 2
updates:
- package-ecosystem: pip
  directory: /ci/scripts
  schedule:
    interval: weekly
    day: "monday"
    time: "09:00"
    timezone: "Europe/Berlin"
  commit-message:
    prefix: "ci"
  labels:
    - run-ci
- package-ecosystem: gomod
  directory: /src/pcap
  schedule:
    interval: weekly
    day: "monday"
    time: "09:00"
    timezone: "Europe/Berlin"
  commit-message:
    prefix: "dep"
  labels:
    - run-ci
- package-ecosystem: gomod
  directory: /acceptance-tests
  schedule:
    interval: weekly
    day: "monday"
    time: "09:00"
    timezone: "Europe/Berlin"
  commit-message:
    prefix: "dep"
  labels:
    - run-ci
