#!/bin/bash
set -euo pipefail

cd "${REPO_ROOT}"

echo "> Running 'bundle exec rake lint'"
bundle install
bundle exec rake lint

echo "> Running 'go vet'"
pushd src/pcap
  go vet ./...
  golangci-lint run
popd
