#!/bin/bash
set -euo pipefail

cd "${REPO_ROOT}"

echo "> Running 'bundle exec rake lint'"
bundle install
bundle exec rake lint

echo "> Running 'go vet' and linter checks for src"
pushd src/pcap
  go vet ./...
  golangci-lint run
popd

# Commented out until we refactored acceptance tests as discussed
#echo "> Running 'go vet' and linter checks for acceptance-tests"
#pushd acceptance-tests
#  go vet ./...
#  golangci-lint run
#popd
