#!/bin/bash

set -euo pipefail

apt-get update && apt-get install -y libpcap-dev # TODO: remove and move to dockerfile

cd "${REPO_ROOT}"

echo "> Running 'bundle exec rake spec'"
bundle package
bundle exec rake spec

echo "> Running unit tests"
pushd src/pcap
  go test $(go list ./... | grep -v /integrationtests)
popd

echo "> Running integration tests"
pushd src/pcap/integrationtests
  ginkgo version
  ginkgo -r -trace
popd
