#!/bin/bash

set -euo pipefail

apt-get update && apt-get install -y libpcap-dev # TODO: remove and move to dockerfile

cd "${REPO_ROOT}"

echo "> Running 'bundle exec rake spec'"
bundle package
bundle exec rake spec

echo "> Running 'go test'"
pushd src/pcap
  go test ./...
popd
