#!/bin/bash

set -euo pipefail

apt-get update && apt-get install -y libpcap-dev # TODO: remove and move to dockerfile

cd "${REPO_ROOT}"

echo "> Running 'bundle exec rake spec'"
bundle package
bundle exec rake spec

echo "> Running unit tests"
pushd src/pcap
  go test $(go list ./... | grep -v /integrationtests)
popd

echo "> Running integration tests"
pushd src/pcap/integrationtests
  mkdir /go
  export GOPATH=/go
  go install "github.com/onsi/ginkgo/v2/ginkgo@latest"
  export PATH=$PATH:$GOPATH/bin
  ginkgo version
  ginkgo -r -trace -vv
popd
