---

pcap_api:
  vm_type: default
  networks: [{name: default}]
  cf_api: https://api.cf.cfapp.com
  ca_path: /cf/pcap_ca
  bosh_director_ca: /bosh/default_ca.ca
  bosh_director_api: https://192.168.1.11:25555
route_registrar:
  public_route: pcap.cf.cfapp.com
nats:
  client_cert: /cf/nats_client_cert.certificate
  client_key: /cf/nats_client_cert.private_key
