id: pcap-api/234
log_level: debug
buffer:
  size: 100
  upper_limit: 95
  lower_limit: 90
concurrent_captures: 5
drain_timeout: 10s
listen:
  port: 8080
  tls: # omitempty -> nil == tls off
    certificate: api-cert.pem
    private_key: api-cert.key
    client_cas: pcap-ca.pem

agents_mtls:
  server_name: pcap-agent.service.cf.internal
  skip_verify: false

  certificate: api-client-cert.pem
  private_key: api-client-cert.key
  ca: pcap-ca.pem

cf:
  cc_url: https://...
  mtls:
    common_name: cloud-controller.service.cf.internal
    skip_verify: false

    certificate: cc-client-cert.pem
    private_key: cc-client-key.key
    ca: cc-ca.pem
bosh:
  director_url: https://bosh.service.cf.internal:8080
  token_scope: bosh.admin
  agent_port: 9494
  tls:
    server_name: bosh.service.cf.internal
    skip_verify: false
    ca: bosh-ca.pem
