// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: pcap.proto

package pcap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// CaptureBosh starts capturing packets on bosh VMs. The capture can be
	// stopped by closing the client-side send channel. The Api MUST listen for
	// that close and MUST stop sending packets as soon as possible but SHOULD
	// send packets that it still receives from the agents.
	CaptureBosh(ctx context.Context, opts ...grpc.CallOption) (Api_CaptureBoshClient, error)
	// CaptureCloudFoundry starts capturing packets on a cloud foundry app. The
	// capture can be stopped by closing the client-side send channel. The Api
	// MUST listen for that close and MUST stop sending packets as soon as
	// possible but SHOULD send packets that it still receives from the agents.
	CaptureCloudfoundry(ctx context.Context, opts ...grpc.CallOption) (Api_CaptureCloudfoundryClient, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/pcap.Api/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CaptureBosh(ctx context.Context, opts ...grpc.CallOption) (Api_CaptureBoshClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[0], "/pcap.Api/CaptureBosh", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiCaptureBoshClient{stream}
	return x, nil
}

type Api_CaptureBoshClient interface {
	Send(*BoshRequest) error
	Recv() (*CaptureResponse, error)
	grpc.ClientStream
}

type apiCaptureBoshClient struct {
	grpc.ClientStream
}

func (x *apiCaptureBoshClient) Send(m *BoshRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *apiCaptureBoshClient) Recv() (*CaptureResponse, error) {
	m := new(CaptureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiClient) CaptureCloudfoundry(ctx context.Context, opts ...grpc.CallOption) (Api_CaptureCloudfoundryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[1], "/pcap.Api/CaptureCloudfoundry", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiCaptureCloudfoundryClient{stream}
	return x, nil
}

type Api_CaptureCloudfoundryClient interface {
	Send(*CloudfoundryRequest) error
	Recv() (*CaptureResponse, error)
	grpc.ClientStream
}

type apiCaptureCloudfoundryClient struct {
	grpc.ClientStream
}

func (x *apiCaptureCloudfoundryClient) Send(m *CloudfoundryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *apiCaptureCloudfoundryClient) Recv() (*CaptureResponse, error) {
	m := new(CaptureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// CaptureBosh starts capturing packets on bosh VMs. The capture can be
	// stopped by closing the client-side send channel. The Api MUST listen for
	// that close and MUST stop sending packets as soon as possible but SHOULD
	// send packets that it still receives from the agents.
	CaptureBosh(Api_CaptureBoshServer) error
	// CaptureCloudFoundry starts capturing packets on a cloud foundry app. The
	// capture can be stopped by closing the client-side send channel. The Api
	// MUST listen for that close and MUST stop sending packets as soon as
	// possible but SHOULD send packets that it still receives from the agents.
	CaptureCloudfoundry(Api_CaptureCloudfoundryServer) error
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedApiServer) CaptureBosh(Api_CaptureBoshServer) error {
	return status.Errorf(codes.Unimplemented, "method CaptureBosh not implemented")
}
func (UnimplementedApiServer) CaptureCloudfoundry(Api_CaptureCloudfoundryServer) error {
	return status.Errorf(codes.Unimplemented, "method CaptureCloudfoundry not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pcap.Api/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CaptureBosh_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiServer).CaptureBosh(&apiCaptureBoshServer{stream})
}

type Api_CaptureBoshServer interface {
	Send(*CaptureResponse) error
	Recv() (*BoshRequest, error)
	grpc.ServerStream
}

type apiCaptureBoshServer struct {
	grpc.ServerStream
}

func (x *apiCaptureBoshServer) Send(m *CaptureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *apiCaptureBoshServer) Recv() (*BoshRequest, error) {
	m := new(BoshRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Api_CaptureCloudfoundry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiServer).CaptureCloudfoundry(&apiCaptureCloudfoundryServer{stream})
}

type Api_CaptureCloudfoundryServer interface {
	Send(*CaptureResponse) error
	Recv() (*CloudfoundryRequest, error)
	grpc.ServerStream
}

type apiCaptureCloudfoundryServer struct {
	grpc.ServerStream
}

func (x *apiCaptureCloudfoundryServer) Send(m *CaptureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *apiCaptureCloudfoundryServer) Recv() (*CloudfoundryRequest, error) {
	m := new(CloudfoundryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pcap.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Api_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CaptureBosh",
			Handler:       _Api_CaptureBosh_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CaptureCloudfoundry",
			Handler:       _Api_CaptureCloudfoundry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pcap.proto",
}

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// Status returns the current status of the agent. It indicates whether the agent is ready to
	// accept new capture requests or is currently unavailable.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Capture(ctx context.Context, opts ...grpc.CallOption) (Agent_CaptureClient, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/pcap.Agent/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Capture(ctx context.Context, opts ...grpc.CallOption) (Agent_CaptureClient, error) {
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], "/pcap.Agent/Capture", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentCaptureClient{stream}
	return x, nil
}

type Agent_CaptureClient interface {
	Send(*AgentRequest) error
	Recv() (*CaptureResponse, error)
	grpc.ClientStream
}

type agentCaptureClient struct {
	grpc.ClientStream
}

func (x *agentCaptureClient) Send(m *AgentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentCaptureClient) Recv() (*CaptureResponse, error) {
	m := new(CaptureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	// Status returns the current status of the agent. It indicates whether the agent is ready to
	// accept new capture requests or is currently unavailable.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Capture(Agent_CaptureServer) error
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAgentServer) Capture(Agent_CaptureServer) error {
	return status.Errorf(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pcap.Agent/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Capture_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).Capture(&agentCaptureServer{stream})
}

type Agent_CaptureServer interface {
	Send(*CaptureResponse) error
	Recv() (*AgentRequest, error)
	grpc.ServerStream
}

type agentCaptureServer struct {
	grpc.ServerStream
}

func (x *agentCaptureServer) Send(m *CaptureResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentCaptureServer) Recv() (*AgentRequest, error) {
	m := new(AgentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pcap.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Agent_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Capture",
			Handler:       _Agent_Capture_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pcap.proto",
}
