#!/usr/bin/env bash

first_line=$(head -n1 "$1")
echo "commit message: $1"

conv_commit_msg="^(fix|feat|build|chore|ci|docs|style|refactor|perf|test)(\(.{1,50}\))?: (.{1,100})\$"
flag=0
if ! [[ "$first_line" =~ (${conv_commit_msg}) ]]; then
    flag=1
    echo "ERROR: Conventional commit message formatting error" >&2
    echo "$first_line" >&2
fi

if [ "$flag" -ne 0 ]; then
  exit 1
fi
