#!/usr/bin/env bash

echo "You are attempting to push to the ${GITHUB_REPO_NAME} repository which has been made read-only"
echo "Access denied, push blocked. Please contact the repository administrator."

exit 0
