---
groups:
  - name: pcap-release
    jobs:
      - unit-tests
      - unit-tests-pr
      - shipit
      - rc

jobs:
  - name: unit-tests
    public: true
    serial: true
    plan:
      - do:
          - get: git
            trigger: true
          - task: lint
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: cf-routing.common.repositories.cloud.sap/pcap-release-testflight
                  tag: latest
                  username: ((docker.username))
                  password: ((docker.password))
              inputs:
                - { name: git }
              caches:
                - path: git/vendor/cache
                - path: git/.bundle
              run:
                path: ./git/ci/scripts/lint
                args: []
              params:
                REPO_ROOT: git
          - task: unit-tests
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: cf-routing.common.repositories.cloud.sap/pcap-release-testflight
                  tag: latest
                  username: ((docker.username))
                  password: ((docker.password))
              inputs:
                - { name: git }

              caches:
                - path: git/vendor/cache
                - path: git/.bundle
              run:
                path: ./git/ci/scripts/unit-tests
                args: []
              params:
                REPO_ROOT: git
        on_failure:
          put: notify
          params:
            channel: "#pcap-release"
            username: ci-bot
            icon_url: "((slack.icon))"
            text: "((slack.fail_url)) pcap-release : unit-tests job failed"

  - name: unit-tests-pr
    public: true
    serial: true
    plan:
      - do:
          - { get: git-pull-requests, trigger: true, version: every }
          - put: git-pull-requests
            params:
              path: git-pull-requests
              status: pending
              context: unit-tests
          - task: lint
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: cf-routing.common.repositories.cloud.sap/pcap-release-testflight
                  tag: latest
                  username: ((docker.username))
                  password: ((docker.password))
              inputs:
                - { name: git-pull-requests }
              caches:
                - path: git-pull-requests/vendor/cache
                - path: git-pull-requests/.bundle
              run:
                path: ./git-pull-requests/ci/scripts/lint
                args: []
              params:
                REPO_ROOT: git-pull-requests
          - task: unit-tests
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: cf-routing.common.repositories.cloud.sap/pcap-release-testflight
                  tag: latest
                  username: ((docker.username))
                  password: ((docker.password))
              inputs:
                - { name: git-pull-requests }
              caches:
                - path: git-pull-requests/vendor/cache
                - path: git-pull-requests/.bundle
              run:
                path: ./git-pull-requests/ci/scripts/unit-tests
                args: []
              params:
                REPO_ROOT: git-pull-requests
    on_success:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: success
        context: unit-tests
    on_failure:
      put: git-pull-requests
      params:
        path: git-pull-requests
        status: failure
        context: unit-tests

  - name: shipit
    public: true
    serial: true
    plan:
    - do:
      - in_parallel:
          - { get: git,     passed: [rc] }
      - task: release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cf-routing.common.repositories.cloud.sap/pcap-release-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - name: git
          outputs:
            - name: gh
          run:
            path: ./git/ci/scripts/shipit
            args: []
          params:
            RELEASE_NAME: pcap-release
            REPO_ROOT:    git
            RELEASE_ROOT: gh
            BRANCH:        main
            GITHUB_OWNER:  cloudfoundry
            GITHUB_TOKEN: ((github.access_token))
            GCP_SERVICE_KEY: ((gcp.service_key))

      - put: blobstore
        params:
          file:  "gh/artifacts/pcap-*.tgz"
      on_failure:
        put: notify
        params:
          channel:  "#pcap-release"
          username: ci-bot
          icon_url: "((slack.icon))"
          text:    "((slack.fail_url)) pcap-boshrelease : shipit job failed"

  - name: rc
    public: true
    serial: true
    plan:
    - do:
      - in_parallel:
          - { get: git,     passed: [unit-tests] }
      - task: release-candidate
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: cf-routing.common.repositories.cloud.sap/pcap-release-testflight
              tag:        latest
              username:   ((docker.username))
              password:   ((docker.password))
          inputs:
            - name: git
          outputs:
            - name: gh
          run:
            path: ./git/ci/scripts/shipit
            args: []
          params:
            RELEASE_NAME: pcap-release
            REPO_ROOT:    git
            RELEASE_ROOT: gh
            BRANCH:        main
            DRY_RUN: true
            GITHUB_OWNER:  cloudfoundry
            GITHUB_TOKEN: ((github.access_token))
            GCP_SERVICE_KEY: ((gcp.service_key))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: git
    type: git
    source:
      uri: git@github.com:cloudfoundry/pcap-release.git
      branch: main
      private_key: ((github.private_key))

  - name: git-pull-requests
    type: pull-request
    source:
      access_token: ((github.access_token))
      repository: cloudfoundry/pcap-release
      base_branch: main
      labels: [run-ci]

  - name: notify
    type: slack-notification
    source:
      url: ((slack.pcap_release_webhook))

  - name: blobstore
    type: gcs
    source:
      bucket:   pcap-release
      json_key: ((gcp.service_key))
      regexp:   pcap-([0-9\.+-]+).tgz
