---
- type: replace
  path: /releases/name=pcap?
  value:
    name: pcap
    version: "1.1.0"
    url: "https://github.com/cloudfoundry/pcap-release/releases/download/v1.1.0/pcap-v1.1.0.tgz"
    sha1: "50444b75da6b6376e8218400145df46d17c4c877"

- type: replace
  path: /addons/name=pcap-agent?/jobs/-
  value:
    name: pcap-agent
    release: pcap
    properties:
      pcap-agent:
        id: pcap-agent
        log_level: "info"
        buffer:
          size: 100
          upper_limit: 95
          lower_limit: 90
        listen:
          port: 9494
          tls:
            certificate: ((pcap_agent.certificate))
            private_key: ((pcap_agent.private_key))
            client_cas: ((pcap_agent.client_cas))
