---
- type: replace
  path: /releases/name=pcap?
  value:
    name: pcap
    version: 0+dev.7
    url: https://github.com/cloudfoundry/pcap-release/releases/download/v0.0.1/pcap-0.0.1.tgz
    sha1: a1655c1992b911fef3ad0b46c5abb8a0217ef0a2

- type: replace
  path: /variables/name=pcap_ca?
  value:
    name: pcap_ca
    type: certificate
    options:
      common_name: pcap_ca
      is_ca: true

- type: replace
  path: /variables/name=pcap_agent_mtls?
  value:
    name: pcap_agent_mtls
    type: certificate
    update_mode: converge
    options:
      ca: pcap_ca
      common_name: pcap_agent_mtls
      alternative_names:
        - pcap-agent.service.cf.internal
      extended_key_usage:
        - client_auth
        - server_auth

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=pcap-agent?
  value:
    name: pcap-agent
    release: pcap
    properties:
      pcap-agent:
        cert: ((pcap_agent_mtls.certificate))
        key: ((pcap_agent_mtls.private_key))
        ca_cert: ((pcap_agent_mtls.ca))
