---
- type: replace
  path: /releases/name=bosh-dns-aliases?
  value:
    name: bosh-dns-aliases
    version: 0.0.4
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.4
    sha1: 55b3dced813ff9ed92a05cda02156e4b5604b273

- type: replace
  path: /releases/-
  value:
    name: routing
    url: https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.268.0
    version: 0.268.0

- type: replace
  path: /releases/-
  value:
    name: bpm
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.21
    version: 1.1.21
    sha1: e8abe19ec186962828de843f8f281cddb6141904

- type: replace
  path: /addons?/-
  value:
    jobs:
      - name: bpm
        release: bpm
    name: bpm

- type: replace
  path: /addons?/-
  value:
    include:
      instance_groups:
        - pcap-api
    jobs:
      - name: bosh-dns-aliases
        release: bosh-dns-aliases
        properties:
          aliases:
          - domain: nats.service.cf.internal
            targets:
              - deployment: cf
                domain: bosh
                instance_group: nats
                network: cf
                query: "*"
          - domain: _.nats.service.cf.internal
            targets:
              - deployment: cf
                domain: bosh
                instance_group: nats
                network: cf
                query: _
    name: bosh-dns-aliases

- type: replace
  path: /instance_groups/name=pcap-api/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats-tls:
        from: nats-tls
        deployment: cf

- type: replace
  path: /instance_groups/name=pcap-api/jobs/name=route_registrar?/properties/route_registrar
  value:
    routes:
      - name: pcap-api-public-endpoint
        protocol: http2
        registration_interval: 20s
        server_cert_domain_san: platform-services.service.cf.internal
        tls_port: 8080
        uris:
          - ((route_registrar.public_route))

- type: replace
  path: /instance_groups/name=pcap-api/jobs/name=route_registrar?/properties/nats
  value:
    tls:
      enabled: true
      client_cert: ((nats.client_cert))
      client_key: ((nats.client_key))

